[CoreLocalisationServiceRegionInformations.NORTHERN_EUROPE]: {
                            id: '2bd03492-9ace-4384-9dd0-34e789a0a644',
                            continent_id: Europe,
                            name: 'NORTHERN EUROPE',
                            name_bn: 'NORTHERN EUROPE',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.SOUTHERN_EUROPE]: {
                            id: '15ec1bf2-44df-4d97-8ff6-2bb7a17a8224',
                            continent_id: Europe,
                            name: 'SOUTHERN EUROPE',
                            name_bn: 'SOUTHERN EUROPE',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.NORTHERN_AFRICA]: {
                            id: '61b1dff6-f1b5-4e67-94c9-704b54a95e5b',
                            continent_id: Africa,
                            name: 'NORTHERN AFRICA',
                            name_bn: 'NORTHERN AFRICA',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.POLYNESIA]: {
                            id: '4927ac80-174b-4cc0-8035-4917645edf48',
                            continent_id: Oceania,
                            name: 'POLYNESIA',
                            name_bn: 'POLYNESIA',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.SUB-SAHARAN_AFRICA]: {
                            id: '0ae1a574-8a84-4d5a-b084-a3965d64a3da',
                            continent_id: Africa,
                            name: 'SUB-SAHARAN AFRICA',
                            name_bn: 'SUB-SAHARAN AFRICA',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.LATIN_AMERICA_AND_THE_CARIBBEAN]: {
                            id: '36624d1d-af76-4510-8e9d-656c0b48982e',
                            continent_id: Americas,
                            name: 'LATIN AMERICA AND THE CARIBBEAN',
                            name_bn: 'LATIN AMERICA AND THE CARIBBEAN',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.]: {
                            id: '261e00c1-c645-4961-a35a-118a4ee9c1c7',
                            continent_id: ,
                            name: '',
                            name_bn: '',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.AUSTRALIA_AND_NEW_ZEALAND]: {
                            id: 'f3d04d5d-112e-401b-8406-f5afccc9cac7',
                            continent_id: Oceania,
                            name: 'AUSTRALIA AND NEW ZEALAND',
                            name_bn: 'AUSTRALIA AND NEW ZEALAND',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.WESTERN_EUROPE]: {
                            id: 'e55c9ebb-7bd0-4cab-9bb8-95cfb2d0b55e',
                            continent_id: Europe,
                            name: 'WESTERN EUROPE',
                            name_bn: 'WESTERN EUROPE',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.EASTERN_EUROPE]: {
                            id: '3cd7c84c-f3c9-4365-86d7-e1b11a6f637f',
                            continent_id: Europe,
                            name: 'EASTERN EUROPE',
                            name_bn: 'EASTERN EUROPE',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.NORTHERN_AMERICA]: {
                            id: '9d7e9fa0-9514-4182-8347-2081a89748a8',
                            continent_id: Americas,
                            name: 'NORTHERN AMERICA',
                            name_bn: 'NORTHERN AMERICA',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.MELANESIA]: {
                            id: 'cd415dfb-7811-456f-b35d-44ecfef9fc39',
                            continent_id: Oceania,
                            name: 'MELANESIA',
                            name_bn: 'MELANESIA',
                            is_active: true,
                            deleted_at: null,
                        },[CoreLocalisationServiceRegionInformations.MICRONESIA]: {
                            id: '35fcb185-124e-4f21-8351-10329574f5e1',
                            continent_id: Oceania,
                            name: 'MICRONESIA',
                            name_bn: 'MICRONESIA',
                            is_active: true,
                            deleted_at: null,
                        },